In [45]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from yahooquery import Ticker
import csv
plt.style.use("seaborn-v0_8")

In [22]:
symbol = "NOK"

In [26]:
nok = yf.Ticker(ticker = symbol)
nok
nok.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-03-27 00:00:00-04:00,4.609270,4.628800,4.550677,4.560443,10818200,0.000,0.0
2023-03-28 00:00:00-04:00,4.540912,4.570208,4.521381,4.570208,10049100,0.000,0.0
2023-03-29 00:00:00-04:00,4.638566,4.648332,4.609270,4.628801,10588000,0.000,0.0
2023-03-30 00:00:00-04:00,4.697159,4.745986,4.687394,4.726455,17342300,0.000,0.0
2023-03-31 00:00:00-04:00,4.745986,4.794813,4.736220,4.794813,9964700,0.000,0.0
2023-04-03 00:00:00-04:00,4.775282,4.794813,4.736220,4.765517,12284100,0.000,0.0
2023-04-04 00:00:00-04:00,4.785048,4.814343,4.745986,4.794813,18041300,0.000,0.0
2023-04-05 00:00:00-04:00,4.794813,4.814343,4.755751,4.785048,11415100,0.000,0.0
2023-04-06 00:00:00-04:00,4.765517,4.785048,4.745986,4.755751,10051600,0.000,0.0
2023-04-10 00:00:00-04:00,4.726455,4.736220,4.677628,4.706924,12969200,0.000,0.0
2023-04-11 00:00:00-04:00,4.804578,4.804578,4.765517,4.775282,11568700,0.000,0.0
2023-04-12 00:00:00-04:00,4.804578,4.824109,4.755751,4.755751,15689800,0.000,0.0
2023-04-13 00:00:00-04:00,4.785048,4.824109,4.785048,4.824109,18075800,0.000,0.0
2023-04-14 00:00:00-04:00,4.833874,4.853405,4.765517,4.785048,16167300,0.000,0.0
2023-04-17 00:00:00-04:00,4.745986,4.755751,4.697159,4.736220,16201200,0.000,0.0
2023-04-18 00:00:00-04:00,4.706924,4.716689,4.482320,4.550677,29728400,0.000,0.0
2023-04-19 00:00:00-04:00,4.560443,4.560443,4.443258,4.511616,32830000,0.000,0.0
2023-04-20 00:00:00-04:00,4.179593,4.199123,4.033112,4.101469,58372900,0.000,0.0
2023-04-21 00:00:00-04:00,4.081938,4.130765,4.062407,4.121000,29375500,0.000,0.0
2023-04-24 00:00:00-04:00,4.220000,4.250000,4.180000,4.200000,23337700,0.099,0.0
2023-04-25 00:00:00-04:00,4.130000,4.140000,4.090000,4.100000,23686800,0.000,0.0
2023-04-26 00:00:00-04:00,4.190000,4.210000,4.140000,4.150000,22908100,0.000,0.0
2023-04-27 00:00:00-04:00,4.140000,4.150000,4.110000,4.120000,7578837,0.000,0.0

In [54]:
nok_info = nok.get_info()
#current_ratio = nok_info['currentRatio']
#print("Current ratio", current_ratio)

# Get the dictionary from nok.get_info()
nok_info = nok.get_info()

# Create a pandas dataframe from the dictionary
df = pd.DataFrame.from_dict(nok_info)

# Export the dataframe to an Excel file
df.to_csv('nok_info.csv', index=False)

In [35]:
fast_info = nok.fast_info
fast_info

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

ValueError: too many values to unpack (expected 2)

In [57]:
yq = Ticker(symbols = "NOK")
yq

In [58]:
yq.key_stats['NOK']

{'maxAge': 1,
 'priceHint': 4,
 'enterpriseValue': 20834682880,
 'forwardPE': 8.438776,
 'profitMargins': 0.16981001,
 'floatShares': 4608539571,
 'sharesOutstanding': 5575680000,
 'sharesShort': 10664308,
 'sharesShortPriorMonth': 13204054,
 'sharesShortPreviousMonthDate': '2023-03-15 02:00:00',
 'dateShortInterest': '2023-04-14 03:00:00',
 'sharesPercentSharesOut': 0.0019,
 'heldPercentInsiders': 7e-05,
 'heldPercentInstitutions': 0.07438,
 'shortRatio': 0.7,
 'beta': 0.696946,
 'impliedSharesOutstanding': 0,
 'category': None,
 'bookValue': 3.821,
 'priceToBook': 1.0821775,
 'fundFamily': None,
 'legalType': None,
 'lastFiscalYearEnd': '2022-12-31 02:00:00',
 'nextFiscalYearEnd': '2023-12-31 02:00:00',
 'mostRecentQuarter': '2023-03-31 03:00:00',
 'earningsQuarterlyGrowth': 0.316,
 'netIncomeToCommon': 4311000064,
 'trailingEps': 0.84,
 'forwardEps': 0.49,
 'pegRatio': 1.44,
 'lastSplitFactor': '4:1',
 'lastSplitDate': '2000-04-11 03:00:00',
 'enterpriseToRevenue': 0.82,
 'enterpriseToEbitda': 5.876,
 '52WeekChange': -0.15306121,
 'SandP52WeekChange': -0.053996503,
 'lastDividendValue': 0.099,
 'lastDividendDate': 1682294400}

In [62]:
with open('dict.csv', 'w') as csv_file:  
    writer = csv.writer(csv_file)
    for key, value in yq.key_stats['NOK'].items():
       writer.writerow([key, value])

In [74]:
d = {k: [v] for k, v in yq.key_stats['NOK'].items()}
pd.DataFrame.from_dict(data=d, orient='columns')

ValueError: Expected 'index', 'columns' or 'tight' for orient parameter. Got 'row' instead

In [72]:

d = {k: [v] for k, v in yq.key_stats['NOK'].items()}
df = pd.DataFrame.from_dict(data=d, orient='columns')
df.to_csv('output.csv', index=False)

In [75]:
nok_info

{'address1': 'Karakaari 7',
 'city': 'Espoo',
 'zip': '02610',
 'country': 'Finland',
 'phone': '358 1044 88000',
 'fax': '358 1044 81002',
 'website': 'https://www.nokia.com',
 'industry': 'Communication Equipment',
 'sector': 'Technology',
 'longBusinessSummary': 'Nokia Oyj provides mobile, fixed, and cloud network solutions worldwide. The company operates through four segments: Network Infrastructure, Mobile Networks, Cloud and Network Services, and Nokia Technologies. It offers products and services for radio access networks and microwave radio links for transport networks, and solutions for network management, as well as network planning, optimization, network deployment, and technical support services. The company provides fixed networking solutions, such as fiber and copper-based access infrastructure, Wi-Fi in-home solutions, and cloud and virtualization services; IP networking solutions, including IP access, aggregation, and edge and core routing for residential, business, mobile, cloud, and digital industry applications, as well as software-defined WAN solutions; a portfolio of optical networks comprising portfolio coherent optical transponders, optical transport network switchers, wavelength-division multiplexers, reconfigurable optical add-drop multiplexer solutions, and optical line systems for metro access and aggregation, data center interconnect, regional, and long-haul/ultra-long-haul applications; and submarine networks. In addition, it offers cloud and network services, including core network solutions, such as voice and packet core; business applications, which covers security, automation, and monetization; cloud and cognitive services; and enterprise solutions covering private wireless and industrial automation. Further, the company provides hardware, software, and services, as well as licensing of intellectual property, including patents, technologies, and the Nokia brand. It serves communications service providers, webscales, hyperscalers, digital industries, and government. Nokia Oyj was founded in 1865 and is headquartered in Espoo, Finland.',
 'fullTimeEmployees': 86896,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Pekka Ilmari Lundmark M.Sc.(Eng.)',
   'age': 59,
   'title': 'Pres & CEO',
   'yearBorn': 1963,
   'fiscalYear': 2022,
   'totalPay': 4445300,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Marco  Wiren M.Sc. (Econ.)',
   'age': 56,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Stephan  Prosi',
   'title': 'VP of Corp. Controlling & Accounting',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nishant  Batra',
   'age': 44,
   'title': 'Chief Strategy & Technology Officer',
   'yearBorn': 1978,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David Terence Mulholland C.F.A.',
   'title': 'Head of Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Esa  Niinimaki',
   'age': 46,
   'title': 'Chief Legal Officer, Corp. & Sec. to the Board',
   'yearBorn': 1976,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy  Hanlon-Rodemich',
   'age': 50,
   'title': 'Chief People Officer',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Maria Rosaria Varsellona J.D., L.L.B.',
   'age': 52,
   'title': 'Exec. Officer',
   'yearBorn': 1970,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Lise  Karstensen',
   'title': 'Head of Nordic&Baltic, Global Enterprise & Public Sector and Country Director of Denmark',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ricky  Corker',
   'age': 55,
   'title': 'Chief Customer Experience Officer',
   'yearBorn': 1967,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 1,
 'boardRisk': 3,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1680307200,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 4,
 'previousClose': 4.15,
 'open': 4.14,
 'dayLow': 4.11,
 'dayHigh': 4.15,
 'regularMarketPreviousClose': 4.15,
 'regularMarketOpen': 4.14,
 'regularMarketDayLow': 4.11,
 'regularMarketDayHigh': 4.15,
 'dividendRate': 0.12,
 'dividendYield': 0.028099999,
 'exDividendDate': 1682294400,
 'payoutRatio': 0.1041,
 'beta': 0.696946,
 'trailingPE': 4.912262,
 'forwardPE': 8.42102,
 'volume': 7605733,
 'regularMarketVolume': 7605733,
 'averageVolume': 17505722,
 'averageVolume10days': 27068370,
 'averageDailyVolume10Day': 27068370,
 'bid': 4.13,
 'ask': 4.14,
 'bidSize': 45100,
 'askSize': 40700,
 'marketCap': 23294570496,
 'fiftyTwoWeekLow': 4.08,
 'fiftyTwoWeekHigh': 5.34,
 'priceToSalesTrailing12Months': 0.91631544,
 'fiftyDayAverage': 4.6664,
 'twoHundredDayAverage': 4.7264,
 'trailingAnnualDividendRate': 0.12,
 'trailingAnnualDividendYield': 0.02891566,
 'currency': 'USD',
 'enterpriseValue': 20834682880,
 'profitMargins': 0.16981001,
 'floatShares': 4608539571,
 'sharesOutstanding': 5575680000,
 'sharesShort': 10664308,
 'sharesShortPriorMonth': 13204054,
 'sharesShortPreviousMonthDate': 1678838400,
 'dateShortInterest': 1681430400,
 'sharesPercentSharesOut': 0.0019,
 'heldPercentInsiders': 7e-05,
 'heldPercentInstitutions': 0.07438,
 'shortRatio': 0.7,
 'impliedSharesOutstanding': 0,
 'bookValue': 3.821,
 'priceToBook': 1.0799005,
 'lastFiscalYearEnd': 1672444800,
 'nextFiscalYearEnd': 1703980800,
 'mostRecentQuarter': 1680220800,
 'earningsQuarterlyGrowth': 0.316,
 'netIncomeToCommon': 4311000064,
 'trailingEps': 0.84,
 'forwardEps': 0.49,
 'pegRatio': 1.44,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 955411200,
 'enterpriseToRevenue': 0.82,
 'enterpriseToEbitda': 5.876,
 '52WeekChange': -0.15306121,
 'SandP52WeekChange': -0.053996503,
 'lastDividendValue': 0.099,
 'lastDividendDate': 1682294400,
 'exchange': 'NYQ',
 'quoteType': 'EQUITY',
 'symbol': 'NOK',
 'underlyingSymbol': 'NOK',
 'shortName': 'Nokia Corporation Sponsored',
 'longName': 'Nokia Oyj',
 'firstTradeDateEpochUtc': 773069400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '9da9d122-fdf0-3b1d-b281-6592e00f28ad',
 'messageBoardId': 'finmb_205573',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 4.1263,
 'targetHighPrice': 8.0,
 'targetLowPrice': 5.02,
 'targetMeanPrice': 6.33,
 'targetMedianPrice': 6.3,
 'recommendationMean': 2.3,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 8,
 'totalCash': 7715999744,
 'totalCashPerShare': 1.386,
 'ebitda': 3545999872,
 'totalDebt': 5342000128,
 'quickRatio': 1.238,
 'currentRatio': 1.549,
 'totalRevenue': 25422000128,
 'debtToEquity': 24.992,
 'revenuePerShare': 4.54,
 'returnOnAssets': 0.039979998,
 'returnOnEquity': 0.21912001,
 'grossProfits': 10306000000,
 'freeCashflow': 206000000,
 'operatingCashflow': 998000000,
 'earningsGrowth': 0.334,
 'revenueGrowth': 0.096,
 'grossMargins': 0.40658,
 'ebitdaMargins': 0.13948,
 'operatingMargins': 0.10381,
 'financialCurrency': 'EUR',
 'trailingPegRatio': None}